name: Check version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_versions_in_notebooks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        topic: ["01_Accessing_Open_Data", "02_Generating_Waveforms", "03_Signal_Processing", "04_Searches", "05_Parameter_Estimation"]

    steps:
    - run: |
        echo "Testing ${{ matrix.topic }} Tutorials on python ${{ matrix.python-version }}"
    - uses: actions/checkout@v4
    - name: Check versions in notebooks
      run: |
        for file in Tutorials/${{ matrix.topic }}/*ipynb; do
            echo "Checking ${file}";
            if ! ./tests/check_versions.py environment.yml "${file}"; then
                echo "::error file=${file},title=Error";
                exit 1;
            fi
        done

  check_environment:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - run: |
        echo "Compare versions in pip requirements file and in conda environment file"
    - uses: actions/checkout@v4
    - name: Compare versions in pip requirements file and in conda environment file
      run: |
        ./tests/check_environment.py requirements.txt environment.yml
